name = "simple_query"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_hackney = ">= 1.3.1 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleamql = { path = "../../../" }
